// SPDX-License-Identifier: GPL-3.0-or-later
// Nominal analog network, 77-0005-01 sheets 8/9. Capacitor-voltage state
// coefficients are generated by tools/prepare_audio_model.py. One shared
// MAC completes the 12 states within the 1000 SYS clocks per audio frame.
// Nominal pots/source scaling and ideal analog assumptions are documented
// in docs/AUDIO_CIRCUIT.md; this does not assert measured PCB voltages.
module victory_audio (
	input  wire                clk, reset, paused, sample_ce,
	input  wire signed [31:0]  speech_input, music_input, effects_input,
	input  wire [8:0]          volume_taps,
	output reg  signed [15:0]  sample,
	output wire signed [31:0]  volume_0, volume_1, volume_2,
	output reg                 busy, overrun
);
localparam integer FRACTION_BITS = 32;
reg signed [35:0] coefficients[0:107];
reg signed [35:0] ladder_coefficients[0:6143];
initial begin
`ifdef VERILATOR
	$readmemh("../rtl/sound/victory_audio_coefficients.hex",coefficients);
	$readmemh("../rtl/sound/victory_ladder_coefficients.hex",ladder_coefficients);
`else
	$readmemh("rtl/sound/victory_audio_coefficients.hex",coefficients);
	$readmemh("rtl/sound/victory_ladder_coefficients.hex",ladder_coefficients);
`endif
end
reg signed [31:0] audio_state[0:8], audio_next[0:8];
reg signed [31:0] ladder_state[0:2], ladder_next[0:2];
reg signed [31:0] previous_input[0:2], input_sum[0:2];
reg signed [35:0] network_coefficient, ladder_coefficient;
reg signed [31:0] operand;
reg signed [71:0] product, accumulator;
reg [3:0] row, column;
reg [8:0] taps;
reg ladder_phase;
wire [12:0] ladder_address = 13'(taps)*13'd12 + 13'(row)*13'd4 + 13'(column);
wire [6:0] network_address = 7'(row)*7'd12 + 7'(column);
wire signed [35:0] coefficient = ladder_phase ? ladder_coefficient : network_coefficient;
// Keep ROM reads outside reset/pause logic: the physical memory output
// registers have no reset. FETCH provides their one-cycle read latency.
always @(posedge clk) begin
	ladder_coefficient <= ladder_coefficients[ladder_address];
	network_coefficient <= coefficients[network_address];
end
typedef enum logic [1:0] {FETCH, MULTIPLY, ACCUMULATE} mac_phase_t;
mac_phase_t mac_phase;
wire signed [71:0] total = accumulator + product;
wire signed [71:0] rounded = (total + 72'sd2147483648) >>> FRACTION_BITS;
wire signed [31:0] next_value = 32'(rounded);
wire signed [63:0] pcm = (64'(next_value) * 64'sd2731) >>> 20;
assign volume_0 = ladder_state[0];
assign volume_1 = ladder_state[1];
assign volume_2 = ladder_state[2];
always @(posedge clk) begin
	if(reset) begin
		for(integer i=0; i<9; i++) begin audio_state[i]<=0; audio_next[i]<=0; end
		for(integer i=0; i<3; i++) begin
			ladder_state[i]<=0; ladder_next[i]<=0; previous_input[i]<=0; input_sum[i]<=0;
		end
		operand<=0; product<=0; accumulator<=0;
		row<=0; column<=0; taps<=0; ladder_phase<=1; mac_phase<=FETCH;
		sample<=0; busy<=0; overrun<=0;
	end else if(!paused) begin
		if(sample_ce) begin
			if(busy) overrun<=1;
			else begin
				input_sum[0] <= speech_input + previous_input[0];
				input_sum[1] <= music_input + previous_input[1];
				input_sum[2] <= effects_input + previous_input[2];
				previous_input[0] <= speech_input;
				previous_input[1] <= music_input;
				previous_input[2] <= effects_input;
				taps<=volume_taps; busy<=1; row<=0; column<=0;
				ladder_phase<=1; mac_phase<=FETCH; accumulator<=0;
			end
		end
		if(busy) begin
			case(mac_phase)
				FETCH: begin
					if(ladder_phase) begin
						operand <= column==3 ? 32'sd1048576 : ladder_state[column[1:0]];
					end else begin
						operand <= column<9 ? audio_state[column] : input_sum[column-9];
					end
					mac_phase <= MULTIPLY;
				end
				MULTIPLY: begin product<=coefficient*operand; mac_phase<=ACCUMULATE; end
				ACCUMULATE: begin
					if(column==(ladder_phase ? 3 : 11)) begin
						if(ladder_phase) ladder_next[row[1:0]] <= 32'(rounded);
						else audio_next[row] <= 32'(rounded);
						accumulator<=0; column<=0;
						if(row==(ladder_phase ? 2 : 8)) begin
							row<=0;
							if(ladder_phase) begin
								ladder_phase<=0;
								ladder_state[0]<=ladder_next[0]; ladder_state[1]<=ladder_next[1];
								ladder_state[2]<=32'(rounded);
							end else begin
								for(integer i=0; i<8; i++) audio_state[i]<=audio_next[i];
								audio_state[8]<=32'(rounded); busy<=0;
								if(pcm>32767) sample<=16'sh7fff;
								else if(pcm< -32768) sample<=16'sh8000;
								else sample<=pcm[15:0];
							end
						end else row<=row+4'd1;
					end else begin accumulator<=total; column<=column+4'd1; end
					mac_phase<=FETCH;
				end
				default: mac_phase<=FETCH;
			endcase
		end
	end
end
endmodule
